// Deterministic generator for fixtures/synthetic/ (ARCHITECTURE §1.15).
//   pnpm tsx scripts/synthetic/generate.ts           write ZIPs + intent files + README
//   pnpm tsx scripts/synthetic/generate.ts --check   exit 1 if committed files differ from a fresh generation
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { groupFamily } from './chats/group-family'
import { groupParents } from './chats/group-parents'
import { privateReexport } from './chats/private-reexport'
import { privateYizhou } from './chats/private-yizhou'
import { buildExports, edgeCases, GENERATOR_VERSION, type ChatScript, type GeneratedExport } from './lib'
import { buildPerfZip, PERF_FILE } from './perf'

export const SCRIPTS: ChatScript[] = [privateYizhou, groupParents, groupFamily]
/** import dedup fixtures (not annotated, not scored): same chat exported twice with media named by export time */
export const REEXPORT_SCRIPTS: ChatScript[] = [privateReexport]
export const OUT_DIR = 'fixtures/synthetic'

export interface GeneratedFile {
  /** path relative to repo root */
  path: string
  bytes: Uint8Array
}

export function generateEvalExports(): GeneratedExport[] {
  return SCRIPTS.flatMap((s) => buildExports(s))
}

export function generateReexportExports(): GeneratedExport[] {
  return REEXPORT_SCRIPTS.flatMap((s) => buildExports(s))
}

/** ZIPs in fixtures/synthetic that are never annotated or scored by `pnpm eval` */
export function notAnnotatedZips(): string[] {
  return [...generateReexportExports().map((e) => e.file), PERF_FILE]
}

const enc = new TextEncoder()

export function generateAll(): GeneratedFile[] {
  const exports = generateEvalExports()
  const reexports = generateReexportExports()
  const perf = buildPerfZip()
  const files: GeneratedFile[] = []
  for (const ex of [...exports, ...reexports]) {
    files.push({ path: `${OUT_DIR}/${ex.file}`, bytes: ex.bytes })
    files.push({ path: `${OUT_DIR}/${ex.file.replace(/\.zip$/, '')}.intent.json`, bytes: enc.encode(JSON.stringify(ex.intent, null, 2) + '\n') })
  }
  files.push({ path: `${OUT_DIR}/${PERF_FILE}`, bytes: perf.bytes })
  const perfEdges = Object.fromEntries(Object.entries(edgeCases(perf.messages)).map(([k, v]) => [k, v.length]))

  type Overlap = { with: string; messages: number; sentAtRange: [string, string]; media: { messages: number; renamed: number } }
  type TextFile = { bom: boolean; lineEnding: string; trailingNewline: boolean }
  const purposeText = (ex: GeneratedExport) => {
    const overlaps = (ex.intent.overlaps as Overlap[]).map(
      (o) => `与 \`${o.with}\` 重叠 ${o.messages} 条消息，${o.sentAtRange[0]} 至 ${o.sentAtRange[1]}${o.media.renamed ? `，其中 ${o.media.renamed} 条图片/视频在两次导出里文件名不同` : ''}`,
    )
    return overlaps.length ? `${ex.purpose}（${overlaps.join('；')}）` : ex.purpose
  }
  const textNote = (ex: GeneratedExport) => {
    const t = ex.intent.textFile as TextFile
    const quirks = [t.bom && 'UTF-8 BOM', t.lineEnding === 'crlf' && 'CRLF 换行', !t.trailingNewline && '文件末尾无换行'].filter(Boolean)
    return quirks.length ? quirks.join('、') : '—'
  }
  const useText = (ex: GeneratedExport) => (ex.use === 'eval' ? 'eval' : 're-export dedup only, not annotated')
  const rows = [...exports, ...reexports].map((ex) => `| \`${ex.file}\` | ${ex.kind === 'private' ? '私聊' : '群聊'} | ${ex.messageCount} | ${ex.dateFrom} → ${ex.dateTo} | ${useText(ex)} | ${purposeText(ex)} | ${textNote(ex)} |`)
  const readme = `# fixtures/synthetic

Generated by \`scripts/synthetic/generate.ts\` (generator v${GENERATOR_VERSION}, deterministic). Do not edit by hand; change the
scripts under \`scripts/synthetic/\` and re-run \`pnpm tsx scripts/synthetic/generate.ts\`. \`--check\` verifies the committed
files match a fresh generation.

Everything here is fictional: people, nicknames, schools-as-person-facts, phone numbers, ID/card numbers and addresses.
Format follows SPEC §6 (iOS "转发到其他应用" export). Message formats that SPEC §6 lists as "未见样本" (quote reply,
recall, contact card, location, file, link, merged forward, group system messages) are **best guesses**.

| file | chat | messages | time range | use | purpose | text file |
|---|---|---|---|---|---|---|
${rows.join('\n')}
| \`${PERF_FILE}\` | 群聊 | ${perf.messages.length} | ${perf.messages[0].sentAt} → ${perf.messages[perf.messages.length - 1].sentAt} | perf only (P1), not annotated | parse-time budget | — |

The two private-chat eval exports are the same chat exported twice with a partial overlap (message dedup, SPEC §8.4).
Their image/video files are named by message time, identically in both exports; their overlap holds no image or video.

The two re-export dedup ZIPs are another chat exported twice the way WeChat really names media: every image/video file is
\`微信图片_<export minute>_<n>.jpg\` / \`微信视频_<export minute>_<n>.mp4\`, so the same photo has a different name in each
export (identical bytes). Their overlap is mostly photos and videos. Importing both into one chat must add no duplicate.

\`<name>.intent.json\` records what the generator planted (facts, negatives, edge cases, expected kinds). It is **not gold**.
Annotators must not open intent files before freezing gold (ARCHITECTURE §7.6).

perf-5000 edge-case counts: ${JSON.stringify(perfEdges)}
`
  files.push({ path: `${OUT_DIR}/README.md`, bytes: enc.encode(readme) })
  return files
}

function sameBytes(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false
  return true
}

export function checkCommitted(root: string, files = generateAll()): string[] {
  const diffs: string[] = []
  for (const f of files) {
    const abs = path.join(root, f.path)
    if (!existsSync(abs)) diffs.push(`missing ${f.path}`)
    else if (!sameBytes(new Uint8Array(readFileSync(abs)), f.bytes)) diffs.push(`differs ${f.path}`)
  }
  return diffs
}

function main() {
  const root = process.cwd()
  const files = generateAll()
  if (process.argv.includes('--check')) {
    const diffs = checkCommitted(root, files)
    if (diffs.length) {
      console.error(diffs.join('\n'))
      process.exit(1)
    }
    console.log(`ok: ${files.length} files match`)
    return
  }
  mkdirSync(path.join(root, OUT_DIR), { recursive: true })
  for (const f of files) {
    writeFileSync(path.join(root, f.path), f.bytes)
    console.log(`${f.path}\t${f.bytes.length} bytes`)
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
