// Private chat between the user (小满) and a university friend (remark name 一舟). Two exports whose windows overlap
// (2026-03-20 … 2026-04-05; the actual message overlap is computed and written to intent/README) — for message dedup (SPEC §8.4) and for job/location changes that supersede earlier facts.
// All names, places of residence, phone numbers and addresses are fictional.
import { PRIVATE_POOL } from '../filler'
import { L, type ChatScript } from '../lib'

const M = 'M'
const Y = 'Y'

export const privateYizhou: ChatScript = {
  id: 'private-yizhou',
  title: '一舟',
  kind: 'private',
  speakers: { M: '小满', Y: '一舟' },
  selfCode: M,
  members: [
    { key: 'xiaoman', label: '小满', displayName: '小满', note: 'self (the user)' },
    { key: 'yizhou', label: '陈一舟', displayName: '一舟', note: 'university friend; remark name in private chat' },
    { key: 'susu', label: '苏苏', note: 'not a sender' },
    { key: 'yizhou_mom', label: '一舟的妈妈', note: 'not a sender' },
    { key: 'duoduo', label: '朵朵', note: "self's daughter; not a sender" },
  ],
  planted: [
    { id: 'y-work-old', type: 'claim', person: 'yizhou', category: 'work', text: '在杭州星禾互娱做前端工程师' },
    { id: 'y-loc-old', type: 'claim', person: 'yizhou', category: 'location', text: '住在杭州滨江' },
    { id: 'y-birthday', type: 'date', person: 'yizhou', text: '生日 11月3日（1995年）', date: { kind: 'birthday', month: 11, day: 3, year: 1995, calendar: 'solar' } },
    { id: 'y-pref-coriander', type: 'claim', person: 'yizhou', category: 'preference', text: '不吃香菜' },
    { id: 'y-edu', type: 'claim', person: 'yizhou', category: 'education', text: '武汉大学计算机系毕业' },
    { id: 'rel-y-susu-partner', type: 'relation', from: 'susu', to: 'yizhou', relationType: 'other', text: '苏苏是一舟的女朋友（2025年11月起）' },
    { id: 'susu-work', type: 'claim', person: 'susu', category: 'work', text: '是自由插画师' },
    { id: 'm-realname', type: 'handle', person: 'xiaoman', handleKind: 'real_name', value: '林小满', text: '真名林小满（出现在地址消息中）', optional: true },
    { id: 'ymom-bday', type: 'date', person: 'yizhou_mom', text: '生日农历正月十八', date: { kind: 'birthday', month: 1, day: 18, calendar: 'lunar' } },
    { id: 'rel-ymom', type: 'relation', from: 'yizhou_mom', to: 'yizhou', relationType: 'parent', text: '一舟的妈妈' },
    { id: 'ymom-neck', type: 'claim', person: 'yizhou_mom', category: 'other', text: '颈椎不好', optional: true },
    { id: 'y-hometown', type: 'claim', person: 'yizhou', category: 'location', text: '老家在江西九江' },
    { id: 'y-running', type: 'claim', person: 'yizhou', category: 'preference', text: '每天早上跑五公里' },
    { id: 'y-halfmarathon', type: 'claim', person: 'yizhou', category: 'life_event', text: '报名了2026年4月杭州马拉松半马', optional: true },
    { id: 'y-work-new', type: 'claim', person: 'yizhou', category: 'work', text: '在深圳蓝鲸出行担任技术负责人', validFrom: '2026-05', supersedes: 'y-work-old' },
    { id: 'y-worked-5y', type: 'claim', person: 'yizhou', category: 'work', text: '在星禾互娱工作了快五年', optional: true },
    { id: 'y-loc-new', type: 'claim', person: 'yizhou', category: 'location', text: '住在深圳南山科技园附近', validFrom: '2026-04', supersedes: 'y-loc-old' },
    { id: 'rel-y-susu-spouse', type: 'relation', from: 'susu', to: 'yizhou', relationType: 'spouse', text: '2026年5月20日领证，苏苏是一舟的妻子' },
    { id: 'y-married', type: 'claim', person: 'yizhou', category: 'life_event', text: '2026年5月20日与苏苏领证结婚', validFrom: '2026-05-20' },
    { id: 'ev-wedding', type: 'event', text: '一舟和苏苏计划10月3日在九江办婚礼', optional: true },
    { id: 'rel-m-duoduo', type: 'relation', from: 'xiaoman', to: 'duoduo', relationType: 'parent', text: '朵朵是小满的女儿' },
    { id: 'susu-studio', type: 'claim', person: 'susu', category: 'work', text: '在深圳南山开了插画工作室', supersedes: 'susu-work', optional: true },
    { id: 'm-edu', type: 'claim', person: 'xiaoman', category: 'education', text: '武汉大学计算机系毕业（与一舟同系）', optional: true },
    // ---- 交互层（SPEC §7 交互层 / §8.8）。loop 的 person 是对方（这段关系属于谁）；text 不带主语，只写事情本身；
    // direction 是「下一步该谁动」：mine = 该我做/该我回答，theirs = 该对方动，mutual = 两个人一起的约定。
    { id: 'loop-dinner-plan', type: 'loop', person: 'yizhou', loopKind: 'plan', direction: 'mutual', text: '下周四晚上一起吃饭', dueAt: '2025-11-06', closedReason: 'done', note: '2025-10-28 约定，2025-11-06 见面兑现；同一批消息也是 negative coord-dinner-plan —— 按 §8.8 分流，不进 claim，进 loop' },
    { id: 'loop-pick-place', type: 'loop', person: 'yizhou', loopKind: 'promise', direction: 'mine', text: '订吃饭的地方', dueAt: '2025-11-06', closedReason: 'done', note: '承诺 2025-10-28 说出口，9 天后 2025-11-06 报出订好的桌号才算了结' },
    { id: 'loop-tea-ship', type: 'loop', person: 'yizhou', loopKind: 'promise', direction: 'theirs', text: '寄龙井茶过来', note: '两次导出里都没有寄到的确认，始终未结' },
    { id: 'loop-interview-later', type: 'loop', person: 'yizhou', loopKind: 'promise', direction: 'mine', text: '回头细说面试安排的看法', note: '在两次导出的重叠区间里' },
    { id: 'loop-move-shenzhen', type: 'loop', person: 'yizhou', loopKind: 'plan', direction: 'theirs', text: '四月底搬去深圳', dueAt: '2026-04', closedReason: 'done', note: '第一次导出结束时仍未结；第二次导出里 2026-04-28「到深圳了」了结' },
    { id: 'loop-photo-question', type: 'loop', person: 'yizhou', loopKind: 'question', direction: 'mine', text: '婚纱照在哪拍的', note: '对方问了我而我没回，所以 direction 是 mine（欠回答的是我）' },
    { id: 'loop-wedding-plan', type: 'loop', person: 'yizhou', loopKind: 'plan', direction: 'mutual', text: '10月3日中午去九江参加婚礼', dueAt: '2026-10-03', note: '婚期在导出结束之后，未结' },
    { id: 'conv-susu', type: 'conversation', text: '一舟说他和苏苏在一起了', topics: ['苏苏', '女朋友', '插画'], note: '会话边界由标注者判定，这里记的是剧本场景的首尾' },
    { id: 'conv-job-change', type: 'conversation', text: '一舟在看新机会', topics: ['换工作', '蓝鲸出行', '深圳'] },
    { id: 'conv-shenzhen', type: 'conversation', text: '一舟到深圳安顿下来', topics: ['深圳', '南山'] },
    { id: 'conv-wedding-date', type: 'conversation', text: '婚礼日期和地点定下来', topics: ['婚礼', '九江', '份子钱'] },
  ],
  negatives: [
    { id: 'coord-dinner-plan', kind: 'coordination', description: '约下周四晚上吃饭' },
    { id: 'coord-at-door', kind: 'coordination', description: '“我在门口”“先进去坐”' },
    { id: 'tx-table', kind: 'transactional', description: '订的6号桌' },
    { id: 'inv-redpacket-bday', kind: 'invisible_content', description: '生日红包，金额不可见', forbidden: '红包金额' },
    { id: 'sens-self-address', kind: 'sensitive', description: '小满发了详细收货地址和手机号', forbidden: '详细地址或手机号进入正文' },
    { id: 'inv-transfer', kind: 'invisible_content', description: '转账金额不可见', forbidden: '转账金额' },
    { id: 'tx-price', kind: 'transactional', description: '按摩仪价格 899、等年货节下单' },
    { id: 'trap-interviewing', kind: 'inference_trap', description: '此时只是在和蓝鲸出行聊，不是已入职', forbidden: '一舟在蓝鲸出行工作（依据3月12日这条）' },
    { id: 'tx-interview-schedule', kind: 'transactional', description: '面试流程时间表' },
    { id: 'inv-redpacket-offer', kind: 'invisible_content', description: '恭喜红包，金额不可见', forbidden: '红包金额' },
    { id: 'inv-voice', kind: 'invisible_content', description: '语音内容不可见', forbidden: '猜测语音内容' },
    { id: 'tx-venue', kind: 'transactional', description: '婚礼酒店地址与时间', forbidden: '酒店详细地址进入正文' },
    { id: 'inv-gift-money', kind: 'invisible_content', description: '份子钱转账，金额不可见', forbidden: '份子钱金额' },
  ],
  sensitiveValues: ['梧桐路88号7栋2单元1502室', '17700001111', '滨江路188号'],
  scenes: [
    {
      at: '2025-10-28 20:14',
      lines: [
        L(Y, '在吗'),
        L(M, '在，咋了'),
        L(Y, '下周我去云杉出差，周三到周五'),
        L(Y, '有空吃个饭？'),
        L(M, '必须的[呲牙]'),
        L(M, '你还在星禾那边？'),
        L(Y, '对，还在星禾互娱写前端，天天加班[流泪]', { p: ['y-work-old'] }),
        L(M, '杭州房租是不是又涨了'),
        L(Y, '涨了，我现在住滨江，通勤半小时', { p: ['y-loc-old'] }),
        L(M, '行，那下周四晚上？', { n: ['coord-dinner-plan'], p: ['loop-dinner-plan'] }),
        L(Y, '可以，你定地方', { n: ['coord-dinner-plan'], p: ['loop-dinner-plan', 'loop-pick-place'] }),
      ],
    },
    {
      at: '2025-11-02 23:40',
      lines: [
        L(M, '明天生日快乐啊，提前祝福🎂', { p: ['y-birthday'] }),
        L(Y, '哈哈谢谢，11月3号，你居然还记得', { p: ['y-birthday'] }),
        L(M, '[微信红包] 生日快乐', { n: ['inv-redpacket-bday'] }),
        L(Y, '[OK]'),
        L(Y, '收到了，破费了'),
        L(M, '三十了吧'),
        L(Y, '别提了，95年的，今年整三十', { p: ['y-birthday'] }),
      ],
    },
    {
      at: '2025-11-06 18:52',
      lines: [
        L(Y, '我到了', { n: ['coord-at-door'], c: ['loop-dinner-plan'] }),
        L(Y, '我在门口', { n: ['coord-at-door'] }),
        L(M, '马上，你先进去坐，报我名字', { n: ['coord-at-door'] }),
        L(M, '订的是 6 号桌', { n: ['tx-table'], c: ['loop-pick-place'] }),
        L(Y, '好'),
        L(Y, '{{img}}'),
        L(Y, '这个酸汤鱼看着不错'),
        L(Y, '不要香菜哈，我是真吃不了香菜', { p: ['y-pref-coriander'] }),
        L(M, '知道知道，大学四年你都是挑出来的', { p: ['y-pref-coriander'] }),
      ],
    },
    {
      at: '2025-11-07 09:12',
      lines: [
        L(Y, '昨天喝多了[捂脸]'),
        L(M, '哈哈哈你酒量还是那样'),
        L(Y, '对了，12月武大计算机系的聚会你去吗', { p: ['y-edu', 'm-edu'] }),
        L(M, '去啊，毕业八年第一次聚', { p: ['m-edu'] }),
        L(Y, '我也请假回武汉，咱们系那帮人好多年没见了', { p: ['y-edu', 'm-edu'] }),
      ],
    },
    {
      at: '2025-11-20 21:05',
      lines: [
        L(Y, '跟你说个事', { p: ['conv-susu'] }),
        L(Y, '我和苏苏在一起了', { p: ['rel-y-susu-partner'] }),
        L(M, '？？？苏苏是谁'),
        L(Y, '之前公司楼下咖啡店认识的，她是做插画的', { p: ['susu-work', 'rel-y-susu-partner'] }),
        L(M, '可以啊，恭喜恭喜'),
        L(M, '[动画表情] 鼓掌'),
        L(Y, '过年带她来云杉见见你们', { p: ['conv-susu'] }),
      ],
    },
    {
      at: '2025-12-10 20:30',
      lines: [
        L(Y, '你家地址再发我一下，给你寄点龙井'),
        L(M, '云杉市青禾区梧桐路88号7栋2单元1502室，林小满，17700001111', { n: ['sens-self-address'], p: ['m-realname'] }),
        L(Y, '好，这周就寄', { p: ['loop-tea-ship'] }),
        L(M, '谢啦[抱拳]'),
        L(Y, '[转账]', { n: ['inv-transfer'] }),
        L(M, '你干嘛转钱'),
        L(Y, '上次吃饭的钱，说好AA的'),
        L(M, '[转账] 朋友已确认收款', { n: ['inv-transfer'] }),
        L(M, '下次不许这样了'),
      ],
    },
    {
      at: '2025-12-24 21:10',
      lines: [
        L(M, '平安夜快乐🍎'),
        L(Y, '[视频通话]'),
        L(M, '刚刚信号不好，挂了'),
        L(Y, '没事，就是想给你看苏苏做的圣诞树'),
        L(Y, '{{vid}}'),
        L(M, '好看！苏苏手真巧'),
      ],
    },
    {
      at: '2026-02-10 22:03',
      lines: [
        L(Y, '我妈生日快到了，农历正月十八，送啥好', { p: ['ymom-bday', 'rel-ymom'] }),
        L(M, '按摩仪？我给我妈买过，她说好用'),
        L(Y, '我妈颈椎确实不好', { p: ['ymom-neck'] }),
        L(Y, '[小程序] 京东购物'),
        L(Y, '这款怎么样'),
        L(M, '可以，评价还行'),
        L(M, '899 有点贵，等年货节再下单', { n: ['tx-price'] }),
      ],
    },
    {
      at: '2026-02-19 11:20',
      lines: [
        L(Y, '我回九江老家了，初六回杭州', { p: ['y-hometown'] }),
        L(M, '带苏苏回去了吗'),
        L(Y, '带了，我妈可喜欢她了'),
        L(Y, '{{img}}'),
        L(Y, '[图片]'),
        L(M, '第二张没发出来'),
        L(Y, '算了不重要'),
      ],
    },
    {
      at: '2026-03-01 07:45',
      lines: [
        L(Y, '我报了杭州马拉松，四月跑半马', { p: ['y-halfmarathon'] }),
        L(M, '你？跑步？'),
        L(Y, '最近每天早上跑五公里，瘦了八斤', { p: ['y-running'] }),
        L(M, '[强]'),
        L(M, '厉害厉害[强][强]'),
      ],
    },
    {
      at: '2026-03-12 22:15',
      lines: [
        L(Y, '最近在看机会', { p: ['conv-job-change'] }),
        L(Y, '星禾今年项目砍了一半，组里走了好多人'),
        L(M, '有方向了吗'),
        L(Y, '深圳有家做出行的在聊，蓝鲸出行，岗位是技术负责人', { n: ['trap-interviewing'] }),
        L(M, '深圳啊，那苏苏怎么办'),
        L(Y, '她是自由插画师，在哪都能接活', { p: ['susu-work', 'conv-job-change'] }),
      ],
    },
    // ---- overlap region of the two exports starts 2026-03-20
    {
      at: '2026-03-22 10:05',
      lines: [
        L(Y, '帮我看看这个面试安排'),
        L(Y, '蓝鲸出行面试流程：\n·3月25日 一面 技术\n·3月27日 二面 架构\n·4月1日 HR面\n2026年04月03日 前后出结果', { n: ['tx-interview-schedule'] }),
        L(M, '挺紧凑的，加油'),
        L(M, '嗯'),
        L(M, '嗯', { dt: 0 }),
        L(Y, '😂 你嗯什么'),
        L(M, '在开会，回头细说', { p: ['loop-interview-later'] }),
      ],
    },
    {
      at: '2026-03-28 19:40',
      lines: [
        L(Y, '二面感觉还行'),
        L(Y, '"一舟"撤回了一条消息'),
        L(M, '[引用] 一舟：二面感觉还行\n那就好，等你好消息'),
        L(Y, '「小满：那就好，等你好消息」\n- - - - - - - - - - - - - - -\n借你吉言[抱拳]'),
      ],
    },
    {
      at: '2026-04-02 12:31',
      lines: [
        L(Y, 'offer 下来了！！！'),
        L(Y, '蓝鲸出行，技术负责人，五月一号入职', { p: ['y-work-new'] }),
        L(M, '恭喜恭喜！！[烟花]'),
        L(M, '[微信红包] 恭喜发财，大吉大利', { n: ['inv-redpacket-offer'] }),
        L(Y, '哈哈哈谢谢老板'),
        L(Y, '这下要搬去深圳了', { p: ['loop-move-shenzhen'] }),
        L(M, '什么时候搬'),
        L(Y, '四月底吧，房子还没找', { p: ['loop-move-shenzhen'] }),
      ],
    },
    {
      at: '2026-04-05 21:40',
      lines: [
        L(Y, '[语音] 23"', { n: ['inv-voice'] }),
        L(Y, '[语音] 8"', { n: ['inv-voice'] }),
        L(M, '地铁上听不了语音，打字吧'),
        L(Y, '就是离职手续办完了，下周五最后一天'),
        L(M, '在星禾待了几年？'),
        L(Y, '快五年了，有点舍不得', { p: ['y-worked-5y'] }),
      ],
    },
    // ---- first export ends 2026-04-05
    {
      at: '2026-04-28 20:02',
      lines: [
        L(Y, '到深圳了', { c: ['loop-move-shenzhen'], p: ['conv-shenzhen'] }),
        L(Y, '暂时住南山科技园附近，走路十分钟到公司', { p: ['y-loc-new'] }),
        L(Y, '[位置] 深圳湾科技生态园'),
        L(M, '以后去深圳有地方蹭饭了'),
        L(Y, '欢迎欢迎，随时来', { p: ['conv-shenzhen'] }),
      ],
    },
    {
      at: '2026-05-20 13:14',
      lines: [
        L(Y, '今天和苏苏领证了💍', { p: ['rel-y-susu-spouse', 'y-married'] }),
        L(M, '啊啊啊啊恭喜！！！'),
        L(M, '婚礼什么时候办'),
        L(Y, '打算国庆回九江办，到时候发请帖', { p: ['ev-wedding'] }),
        L(M, '一定到'),
        L(Y, '[名片] 苏苏'),
        L(Y, '加一下苏苏，她想问你婚纱照在哪拍的', { p: ['loop-photo-question'] }),
        L(M, '好的马上加'),
      ],
    },
    {
      at: '2026-06-14 22:40',
      lines: [
        L(Y, '[链接] 深圳租房避坑指南 https://example.com/articles/sz-rent'),
        L(Y, '转你看看，你之前不是也想换房子'),
        L(M, '我晚上看'),
        L(Y, '[文件] 婚礼流程v2.docx'),
        L(Y, '苏苏写的流程，你帮忙挑挑毛病'),
        L(M, '好'),
        L(Y, '[视频号] 周末去大鹏徒步 https://channels.weixin.qq.com/web/pages/feed?eid=synthetic-0001'),
        L(M, '风景好好'),
        L(Y, '[音乐] 小幸运'),
        L(M, '你这歌单还停在大学'),
      ],
    },
    {
      at: '2026-07-09 23:05',
      lines: [
        L(M, '我闺女朵朵这两天发烧，折腾死了', { p: ['rel-m-duoduo'] }),
        L(Y, '小孩换季容易生病，多喝水多睡觉'),
        L(M, '嗯嗯，已经退烧了'),
      ],
    },
    {
      at: '2026-08-18 19:30',
      lines: [
        L(Y, '苏苏在南山开了个插画工作室，下周开业', { p: ['susu-studio'] }),
        L(Y, '{{img:missing}}'),
        L(M, '图片没加载出来'),
        L(Y, '就是门头照，回头你来看'),
        L(M, '帮我跟苏苏说声恭喜'),
      ],
    },
    {
      at: '2026-09-01 21:00',
      lines: [
        L(Y, '婚礼定了，10月3号中午，九江', { p: ['ev-wedding', 'loop-wedding-plan', 'conv-wedding-date'] }),
        L(Y, '酒店地址：九江市浔阳区滨江路188号锦江酒店三楼宴会厅', { n: ['tx-venue'] }),
        L(Y, '{{img}}'),
        L(M, '我请好假了', { p: ['loop-wedding-plan'] }),
        L(M, '[转账]', { n: ['inv-gift-money'] }),
        L(Y, '你这是干嘛，人来就行'),
        L(M, '份子钱先给你', { n: ['inv-gift-money'] }),
        L(Y, '那我收下了，谢谢小满', { p: ['conv-wedding-date'] }),
      ],
    },
    {
      at: '2026-09-14 20:45',
      lines: [
        L(Y, '下周回杭州出差，去老东家交接点东西'),
        L(M, '替我向西湖问好'),
        L(Y, '👌'),
        L(M, '[OK]'),
        L(M, '那你今晚早点休息'),
      ],
    },
  ],
  filler: { seed: 20260405, count: 70, from: '2025-10-20', to: '2026-09-13', pool: PRIVATE_POOL, speakers: [M, Y], minRepeatGapDays: 30 },
  exports: [
    { file: '聊天记录_20260405_223012.zip', from: '2025-10-01 00:00', to: '2026-04-05 23:59', purpose: '私聊，第一次导出' },
    { file: '聊天记录_20260914_211545.zip', from: '2026-03-20 00:00', to: '2026-09-14 23:59', purpose: '私聊，第二次导出' },
  ],
}
